snowflake:
  node:
    large: 1023-1023
    small: 1023-1023

server:
  compression:
    enabled: false
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 1010
logging:
  level:
    com.tinkertian: debug
  path: logs
  file:
    max-size: 100MB
spring:
  profiles:
    active: dev